# Generated by Django 3.1.1 on 2020-10-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=80)),
                ('localidad', models.CharField(max_length=80)),
                ('denominacion', models.CharField(max_length=80)),
                ('nombre', models.CharField(max_length=80)),
                ('codigo', models.IntegerField()),
                ('tipo', models.CharField(max_length=80)),
                ('direccion', models.CharField(max_length=80)),
                ('codigo_postal', models.IntegerField()),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
