//STUDENTS
export const GET_STUDENTS = "GET_STUDENTS";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const ADD_STUDENT = "ADD_STUDENT";

// MESSAGES
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

// USER
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_SCHOOLS = "GET_SCHOOLS";
export const GET_GRADES = "GET_GRADES";
export const VALIDATE_USER = "VALIDATE_USER";
export const GET_EXTENDED_USER_SUCCESS = "GET_EXTENDED_USER_SUCCESS";


//TESTS
export const CODE_CHECKED = "CODE_CHECKED";
export const CODE_FAILED = "CODE_FAILED";

//PASSWORD
export const RESET_PASSWORD_SENT = "RESET_PASSWORD_SENT";
export const RESET_PASSWORD_CHECK_SUCCESS = "RESET_PASSWORD_CHECK_SUCCESS";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const CHECK_VALIDATION_SUCCESS = "CHECK_VALIDATION_SUCCESS";
export const CHECK_VALIDATION_FAIL = "CHECK_VALIDATION_FAIL"
export const CHECK_ACCOUNT_SUCCESS = "CHECK_ACCOUNT_SUCCESS";

// ROLES
export const ROLES_LOADED = "ROLES_LOADED"

// ADMIN
export const GET_STUDENTS_ADMIN = "GET_STUDENTS_ADMIN"